prompt PL/SQL Developer Export Tables for user KFRAULI@LOCALHOST:1521/FREE
prompt Created by Kenneth on miércoles, 12 de noviembre de 2025
set feedback off
set define off

prompt Dropping CONSULTORIO...
drop table CONSULTORIO cascade constraints;
prompt Dropping MEDICO...
drop table MEDICO cascade constraints;
prompt Dropping HORARIO_MEDICO...
drop table HORARIO_MEDICO cascade constraints;
prompt Dropping PACIENTE...
drop table PACIENTE cascade constraints;
prompt Dropping SERVICIO...
drop table SERVICIO cascade constraints;
prompt Dropping RESERVA...
drop table RESERVA cascade constraints;
prompt Creating CONSULTORIO...
create table CONSULTORIO
(
  id        NUMBER generated by default as identity,
  nombre    VARCHAR2(60) not null,
  piso      VARCHAR2(10),
  capacidad NUMBER default 1
)
tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table CONSULTORIO
  add constraint PK_CONSULTORIO primary key (ID)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table CONSULTORIO
  add constraint CK_CONSULTORIO_CAPACIDAD
  check (CAPACIDAD >= 1);

prompt Creating MEDICO...
create table MEDICO
(
  id           NUMBER generated by default as identity,
  nombre       VARCHAR2(100) not null,
  especialidad VARCHAR2(100),
  colegiado    VARCHAR2(30),
  email        VARCHAR2(120),
  telefono     VARCHAR2(30)
)
tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table MEDICO
  add constraint PK_MEDICO primary key (ID)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table MEDICO
  add constraint UK_MEDICO_COLEGIADO unique (COLEGIADO)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

prompt Creating HORARIO_MEDICO...
create table HORARIO_MEDICO
(
  id          NUMBER generated by default as identity,
  medico_id   NUMBER not null,
  dia_semana  NUMBER not null,
  hora_inicio VARCHAR2(5 CHAR) not null,
  hora_fin    VARCHAR2(5 CHAR) not null
)
tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table HORARIO_MEDICO
  add constraint PK_HORARIO_MEDICO primary key (ID)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table HORARIO_MEDICO
  add constraint UK_HORARIO_MEDICO_RANGO unique (MEDICO_ID, DIA_SEMANA, HORA_INICIO, HORA_FIN)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table HORARIO_MEDICO
  add constraint FK_HORARIO_MEDICO__MEDICO foreign key (MEDICO_ID)
  references MEDICO (ID);
alter table HORARIO_MEDICO
  add constraint CK_HORARIO_DIA_SEMANA
  check (DIA_SEMANA BETWEEN 1 AND 7);

prompt Creating PACIENTE...
create table PACIENTE
(
  id        NUMBER generated by default as identity,
  nombre    VARCHAR2(100) not null,
  cedula    VARCHAR2(30),
  fecha_nac DATE,
  email     VARCHAR2(120),
  telefono  VARCHAR2(30)
)
tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table PACIENTE
  add constraint PK_PACIENTE primary key (ID)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table PACIENTE
  add constraint UK_PACIENTE_CEDULA unique (CEDULA)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

prompt Creating SERVICIO...
create table SERVICIO
(
  id           NUMBER generated by default as identity,
  nombre       VARCHAR2(100) not null,
  duracion_min NUMBER not null,
  precio       NUMBER(10,2) not null
)
tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table SERVICIO
  add constraint PK_SERVICIO primary key (ID)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

prompt Creating RESERVA...
create table RESERVA
(
  id             NUMBER generated by default as identity,
  paciente_id    NUMBER not null,
  medico_id      NUMBER not null,
  servicio_id    NUMBER not null,
  consultorio_id NUMBER not null,
  fecha          DATE not null,
  hora_inicio    VARCHAR2(5 CHAR) not null,
  hora_fin       VARCHAR2(5 CHAR) not null,
  estado         VARCHAR2(20) default 'CONFIRMADA',
  codigo         VARCHAR2(16)
)
tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create index IDX_RESERVA_CAL on RESERVA (MEDICO_ID, FECHA, HORA_INICIO)
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create index IDX_RESERVA_CONSULTORIO on RESERVA (CONSULTORIO_ID, FECHA, HORA_INICIO)
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table RESERVA
  add constraint PK_RESERVA primary key (ID)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table RESERVA
  add constraint UK_RESERVA_CODIGO unique (CODIGO)
  using index
  tablespace PROYECTOPROGRA3
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table RESERVA
  add constraint FK_RESERVA__CONSULTORIO foreign key (CONSULTORIO_ID)
  references CONSULTORIO (ID);
alter table RESERVA
  add constraint FK_RESERVA__MEDICO foreign key (MEDICO_ID)
  references MEDICO (ID);
alter table RESERVA
  add constraint FK_RESERVA__PACIENTE foreign key (PACIENTE_ID)
  references PACIENTE (ID);
alter table RESERVA
  add constraint FK_RESERVA__SERVICIO foreign key (SERVICIO_ID)
  references SERVICIO (ID);
alter table RESERVA
  add constraint CK_RESERVA_ESTADO
  check (ESTADO IN ('PENDIENTE','CONFIRMADA','CANCELADA'));

prompt Disabling triggers for CONSULTORIO...
alter table CONSULTORIO disable all triggers;
prompt Disabling triggers for MEDICO...
alter table MEDICO disable all triggers;
prompt Disabling triggers for HORARIO_MEDICO...
alter table HORARIO_MEDICO disable all triggers;
prompt Disabling triggers for PACIENTE...
alter table PACIENTE disable all triggers;
prompt Disabling triggers for SERVICIO...
alter table SERVICIO disable all triggers;
prompt Disabling triggers for RESERVA...
alter table RESERVA disable all triggers;
prompt Disabling foreign key constraints for HORARIO_MEDICO...
alter table HORARIO_MEDICO disable constraint FK_HORARIO_MEDICO__MEDICO;
prompt Disabling foreign key constraints for RESERVA...
alter table RESERVA disable constraint FK_RESERVA__CONSULTORIO;
alter table RESERVA disable constraint FK_RESERVA__MEDICO;
alter table RESERVA disable constraint FK_RESERVA__PACIENTE;
alter table RESERVA disable constraint FK_RESERVA__SERVICIO;
prompt Loading CONSULTORIO...
insert into CONSULTORIO (id, nombre, piso, capacidad)
values (1, 'Consul-101', '1', 1);
insert into CONSULTORIO (id, nombre, piso, capacidad)
values (2, 'Consul-201', '2', 1);
commit;
prompt 2 records loaded
prompt Loading MEDICO...
insert into MEDICO (id, nombre, especialidad, colegiado, email, telefono)
values (1, 'Dra. Ana Solís', 'Medicina General', 'MG-1234', 'ana.solis@clinicacr.com', '65342428');
insert into MEDICO (id, nombre, especialidad, colegiado, email, telefono)
values (2, 'Dr. Luis Pineda', 'Pediatría', 'PD-5678', 'luis.pineda@clinicacr.com', '84352344');
insert into MEDICO (id, nombre, especialidad, colegiado, email, telefono)
values (41, 'Dr.Carlos Monge', 'Urologo', 'LF-3322', 'carlos.monge@clinicacr.com', '82342346');
commit;
prompt 3 records loaded
prompt Loading HORARIO_MEDICO...
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (1, 1, 1, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (2, 1, 1, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (3, 1, 2, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (4, 1, 2, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (5, 1, 3, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (6, 1, 3, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (7, 1, 4, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (8, 1, 4, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (9, 1, 5, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (10, 1, 5, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (11, 2, 1, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (12, 2, 1, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (13, 2, 2, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (14, 2, 2, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (15, 2, 3, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (16, 2, 3, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (17, 2, 4, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (18, 2, 4, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (19, 2, 5, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (20, 2, 5, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (21, 41, 1, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (26, 41, 1, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (22, 41, 2, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (27, 41, 2, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (23, 41, 3, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (28, 41, 3, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (24, 41, 4, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (29, 41, 4, '13:00', '17:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (25, 41, 5, '08:00', '12:00');
insert into HORARIO_MEDICO (id, medico_id, dia_semana, hora_inicio, hora_fin)
values (30, 41, 5, '13:00', '17:00');
commit;
prompt 30 records loaded
prompt Loading PACIENTE...
insert into PACIENTE (id, nombre, cedula, fecha_nac, email, telefono)
values (1, 'María Rojas', '1-1111-1111', to_date('10-03-1995', 'dd-mm-yyyy'), 'maria.rojas@mail.com', '7200-2001');
insert into PACIENTE (id, nombre, cedula, fecha_nac, email, telefono)
values (2, 'Carlos Méndez', '2-2222-2222', to_date('25-07-1992', 'dd-mm-yyyy'), 'carlos.mendez@mail.com', '7200-2002');
insert into PACIENTE (id, nombre, cedula, fecha_nac, email, telefono)
values (3, 'Ana Quesada', '3-3333-3333', to_date('01-12-1988', 'dd-mm-yyyy'), 'ana.quesada@mail.com', '7200-2003');
commit;
prompt 3 records loaded
prompt Loading SERVICIO...
insert into SERVICIO (id, nombre, duracion_min, precio)
values (1, 'Consulta General', 30, 25000);
insert into SERVICIO (id, nombre, duracion_min, precio)
values (2, 'Control Pediátrico', 30, 28000);
insert into SERVICIO (id, nombre, duracion_min, precio)
values (3, 'Electrocardiograma', 45, 35000);
insert into SERVICIO (id, nombre, duracion_min, precio)
values (21, 'Urologia', 35, 15000);
commit;
prompt 4 records loaded
prompt Loading RESERVA...
insert into RESERVA (id, paciente_id, medico_id, servicio_id, consultorio_id, fecha, hora_inicio, hora_fin, estado, codigo)
values (1, 1, 1, 1, 1, to_date('05-11-2025', 'dd-mm-yyyy'), '09:30', '10:00', 'CONFIRMADA', 'R-AB12CD34EF56');
insert into RESERVA (id, paciente_id, medico_id, servicio_id, consultorio_id, fecha, hora_inicio, hora_fin, estado, codigo)
values (41, 1, 1, 1, 1, to_date('12-11-2025', 'dd-mm-yyyy'), '08:00', '08:30', 'CONFIRMADA', 'R-26DE1A00EDE543');
insert into RESERVA (id, paciente_id, medico_id, servicio_id, consultorio_id, fecha, hora_inicio, hora_fin, estado, codigo)
values (42, 2, 41, 21, 1, to_date('12-11-2025', 'dd-mm-yyyy'), '13:00', '13:35', 'CONFIRMADA', 'R-F688454C082143');
insert into RESERVA (id, paciente_id, medico_id, servicio_id, consultorio_id, fecha, hora_inicio, hora_fin, estado, codigo)
values (43, 3, 2, 2, 2, to_date('12-11-2025', 'dd-mm-yyyy'), '10:00', '10:30', 'CONFIRMADA', 'R-82E10E5E0D2748');
insert into RESERVA (id, paciente_id, medico_id, servicio_id, consultorio_id, fecha, hora_inicio, hora_fin, estado, codigo)
values (45, 2, 1, 1, 2, to_date('12-11-2025', 'dd-mm-yyyy'), '11:00', '11:30', 'CONFIRMADA', 'R-86A96320852948');
commit;
prompt 5 records loaded
prompt Enabling foreign key constraints for HORARIO_MEDICO...
alter table HORARIO_MEDICO enable constraint FK_HORARIO_MEDICO__MEDICO;
prompt Enabling foreign key constraints for RESERVA...
alter table RESERVA enable constraint FK_RESERVA__CONSULTORIO;
alter table RESERVA enable constraint FK_RESERVA__MEDICO;
alter table RESERVA enable constraint FK_RESERVA__PACIENTE;
alter table RESERVA enable constraint FK_RESERVA__SERVICIO;
prompt Enabling triggers for CONSULTORIO...
alter table CONSULTORIO enable all triggers;
prompt Enabling triggers for MEDICO...
alter table MEDICO enable all triggers;
prompt Enabling triggers for HORARIO_MEDICO...
alter table HORARIO_MEDICO enable all triggers;
prompt Enabling triggers for PACIENTE...
alter table PACIENTE enable all triggers;
prompt Enabling triggers for SERVICIO...
alter table SERVICIO enable all triggers;
prompt Enabling triggers for RESERVA...
alter table RESERVA enable all triggers;

set feedback on
set define on
prompt Done

prompt Creando trigger TR_RESERVA_BIU (validación de reservas)...
CREATE OR REPLACE TRIGGER TR_RESERVA_BIU
BEFORE INSERT OR UPDATE ON RESERVA
FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  IF :NEW.HORA_FIN IS NULL THEN
    SELECT TO_CHAR(
             TO_DATE(:NEW.HORA_INICIO,'HH24:MI') +
             (duracion_min / (24*60)),
             'HH24:MI'
           )
    INTO :NEW.HORA_FIN
    FROM SERVICIO
    WHERE id = :NEW.SERVICIO_ID;
  END IF;

  SELECT COUNT(*)
  INTO v_count
  FROM RESERVA r
  WHERE r.MEDICO_ID = :NEW.MEDICO_ID
    AND r.FECHA     = :NEW.FECHA
    AND r.ID        <> NVL(:NEW.ID,-1)
    AND r.ESTADO   <> 'CANCELADA'
    AND TO_DATE(r.HORA_INICIO,'HH24:MI') < TO_DATE(:NEW.HORA_FIN,'HH24:MI')
    AND TO_DATE(:NEW.HORA_INICIO,'HH24:MI') < TO_DATE(r.HORA_FIN,'HH24:MI');

  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(
      -20001,
      'Traslape de reserva para el médico en ese horario.'
    );
  END IF;
END;
/

prompt Ajustando identity de MEDICO...
DECLARE
  v_next NUMBER;
BEGIN
  SELECT NVL(MAX(id),0) + 1 INTO v_next FROM MEDICO;
  EXECUTE IMMEDIATE
    'ALTER TABLE MEDICO MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||')';
END;

/
prompt Ajustando identity de PACIENTE...
DECLARE
  v_next NUMBER;
BEGIN
  SELECT NVL(MAX(id),0) + 1 INTO v_next FROM PACIENTE;
  EXECUTE IMMEDIATE
    'ALTER TABLE PACIENTE MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||')';
END;
/

prompt Ajustando identity de SERVICIO...
DECLARE
  v_next NUMBER;
BEGIN
  SELECT NVL(MAX(id),0) + 1 INTO v_next FROM SERVICIO;
  EXECUTE IMMEDIATE
    'ALTER TABLE SERVICIO MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||')';
END;
/

prompt Ajustando identity de CONSULTORIO...
DECLARE
  v_next NUMBER;
BEGIN
  SELECT NVL(MAX(id),0) + 1 INTO v_next FROM CONSULTORIO;
  EXECUTE IMMEDIATE
    'ALTER TABLE CONSULTORIO MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||')';
END;
/

prompt Ajustando identity de HORARIO_MEDICO...
DECLARE
  v_next NUMBER;
BEGIN
  SELECT NVL(MAX(id),0) + 1 INTO v_next FROM HORARIO_MEDICO;
  EXECUTE IMMEDIATE
    'ALTER TABLE HORARIO_MEDICO MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||')';
END;
/
prompt Ajustando identity de RESERVA...
DECLARE
  v_next NUMBER;
BEGIN
  SELECT NVL(MAX(id),0) + 1 INTO v_next FROM RESERVA;
  EXECUTE IMMEDIATE
    'ALTER TABLE RESERVA MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH '||v_next||')';
END;
/

CREATE OR REPLACE NONEDITIONABLE TRIGGER TR_RESERVA_BIU
BEFORE INSERT OR UPDATE ON RESERVA
FOR EACH ROW
DECLARE
  v_duracion  SERVICIO.DURACION_MIN%TYPE;
BEGIN
  IF :NEW.SERVICIO_ID IS NOT NULL THEN
    SELECT DURACION_MIN
      INTO v_duracion
      FROM SERVICIO
     WHERE ID = :NEW.SERVICIO_ID;

    IF :NEW.HORA_FIN IS NULL
       OR INSERTING
       OR UPDATING('SERVICIO_ID')
       OR UPDATING('HORA_INICIO')
    THEN
      :NEW.HORA_FIN :=
        TO_CHAR(
          TO_DATE(:NEW.HORA_INICIO, 'HH24:MI')
          + NUMTODSINTERVAL(v_duracion, 'MINUTE'),
          'HH24:MI'
        );
    END IF;
  END IF;

  IF TO_DATE(:NEW.HORA_INICIO, 'HH24:MI')
     >= TO_DATE(:NEW.HORA_FIN, 'HH24:MI')
  THEN
    RAISE_APPLICATION_ERROR(-20000,
      'HORA_INICIO debe ser menor que HORA_FIN.');
  END IF;
END;
/

