spring.application.name=webservice
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.username=KFRAULI
spring.datasource.password=frauli
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false
spring.flyway.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


server.port=8081


# Puerto/host del servidor de sockets
socket.availability.port=9090
socket.availability.bind=0.0.0.0
socket.availability.poolSize=16
socket.availability.clientIdleTimeoutSec=60
